version: "3.8"

services:
  # =========================
  # 🔥 APP INSTANCES
  # =========================
  app1:
    image: ${DOCKER_USERNAME}/springboot-cicd:${IMAGE_TAG}
    container_name: app1
    environment:
      - INSTANCE_ID=app1
    restart: always

  app2:
    image: ${DOCKER_USERNAME}/springboot-cicd:${IMAGE_TAG}
    container_name: app2
    environment:
      - INSTANCE_ID=app2
    restart: always

  app3:
    image: ${DOCKER_USERNAME}/springboot-cicd:${IMAGE_TAG}
    container_name: app3
    environment:
      - INSTANCE_ID=app3
    restart: always

  # =========================
  # 🌐 NGINX LOAD BALANCER
  # =========================
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
      - app3

