server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker

    pipeline_stages:
      - docker: {}

    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

    # 🔥 GẮN LABEL CONTAINER
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'

      # 🔥 CHỈ GIỮ app1, app2, app3
      - source_labels: ['__meta_docker_container_name']
        regex: '/(app1|app2|app3)'
        action: keep